sharetribe/config/routes.rb
Rails.application.routes.draw do

  namespace :mercury do
    resources :images
  end

  mount Mercury::Engine => '/'

  get "/robots.txt" => RobotsGenerator

  get "/sitemap.xml.gz"                        => "sitemap#sitemap", format: :xml
  get "/sitemap/:sitemap_host/generate.xml.gz" => "sitemap#generate", format: :xml, :constraints => { sitemap_host: /[.\-\w]+/ }

  get "/:dv_file" => "domain_validation#index", constraints: {dv_file: /.*\.txt/}

  get "/design" => "design#design"

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  post '/webhooks/paypal_ipn' => 'paypal_ipn#ipn_hook', as: :paypal_ipn_hook
  post '/webhooks/plans' => 'plans#create'
  get '/webhooks/trials' => 'plans#get_trials'

  post '/bounces' => 'amazon_bounces#notification'

  get "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  get "/listings/new/:type" => "listings#new", :as => :new_request_without_locale # needed for some emails, where locale part is already set
  get "/change_locale" => "i18n#change_locale", :as => :change_locale

  namespace :int_api do
    post "/create_trial_marketplace" => "marketplaces#create"
    post "/prospect_emails" => "marketplaces#create_prospect_email"
    resources :listings, only: [], defaults: { format: :json } do
      member do
        post :update_working_time_slots
      end
    end
  end

  match '/harmony_proxy/*harmony_path' => 'harmony_proxy#proxy', via: :all

  get "/ui_api/topbar_props" => "topbar_api#props"

  get '/_lp_preview' => 'landing_page#preview'

  locale_regex_string = Sharetribe::AVAILABLE_LOCALES.map { |l| l[:ident] }.concat(Sharetribe::REMOVED_LOCALES.to_a).join("|")
  locale_matcher = Regexp.new(locale_regex_string)
  locale_matcher_anchored = Regexp.new("^(#{locale_regex_string})$")

  get '/:locale/' => 'landing_page#index', as: :landing_page_with_locale, constraints: ->(request) {
    locale_matcher_anchored.match(request.params["locale"]) &&
      CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }
  get '/' => 'landing_page#index', as: :landing_page_without_locale, constraints: ->(request) {
    CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }

  get '/:locale/s' => 'homepage#index', as: :search_with_locale, constraints: ->(request) {
    locale_matcher_anchored.match(request.params["locale"]) &&
      CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }
  get '/s' => 'homepage#index', as: :search_without_locale, constraints: ->(request) {
    CustomLandingPage::LandingPageStore.enabled?(request.env[:current_marketplace]&.id)
  }

  get '/:locale/' => 'homepage#index', :constraints => { :locale => locale_matcher }, as: :homepage_with_locale
  get '/' => 'homepage#index', as: :homepage_without_locale
  get '/:locale/s', to: redirect('/%{locale}', status: 307), constraints: { locale: locale_matcher }
  get '/s', to: redirect('/', status: 307)

  get '/500' => 'errors#server_error'
  get '/404' => 'errors#not_found', :as => :error_not_found
  get '/406' => 'errors#not_acceptable', :as => :error_not_acceptable
  get '/410' => 'errors#gone', as: :error_gone
  get '/community_not_found' => 'errors#community_not_found', as: :community_not_found

  resources :communities, only: [:new, :create]

  devise_for :people, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "sessions" }

  scope "(/:locale)", :constraints => { :locale => locale_matcher } do

    put '/mercury_update' => "mercury_update#update", :as => :mercury_update

    get "/transactions/op_status/:process_token" => "transactions#paypal_op_status", as: :paypal_op_status
    get "/transactions/transaction_op_status/:process_token" => "transactions#transaction_op_status", :as => :transaction_op_status
    get "/transactions/created/:transaction_id" => "transactions#created", as: :transaction_created
    get "/transactions/finalize_processed/:process_token" => "transactions#finalize_processed", as: :transaction_finalize_processed

    get "/transactions/new" => "transactions#new", as: :new_transaction

    get "/listings/:listing_id/book", :to => redirect { |params, request|
      "/#{params[:locale]}/listings/#{params[:listing_id]}/initiate?#{request.query_string}"
    }
    post "/listings/:listing_id/booked"    => "preauthorize_transactions#initiated", as: :booked # POST request, no redirect

    get "/listings/:listing_id/initiate"   => "preauthorize_transactions#initiate", :as => :initiate_order
    post "/listings/:listing_id/initiated" => "preauthorize_transactions#initiated", :as => :initiated_order

    post "/listings/:listing_id/create_contact" => "free_transactions#create_contact", :as => :create_contact
    get "/listings/:listing_id/contact" => "free_transactions#contact", :as => :contact_to_listing

    get "/logout" => "sessions#destroy", :as => :logout
    get "/confirmation_pending" => "community_memberships#confirmation_pending", :as => :confirmation_pending
    get "/login" => "sessions#new", :as => :login
    get "/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
    get "/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
    get '/:person_id/settings/payments' => 'payment_settings#index', :as => :person_payment_settings
    post '/:person_id/settings/payments' => 'payment_settings#update', :as => :update_person_payment_settings
    get '/:person_id/settings/payments/paypal_account' => 'paypal_accounts#index', :as => :paypal_account_settings_payment

    get  '/community_memberships/pending_consent' => 'community_memberships#pending_consent', as: :pending_consent
    post '/community_memberships/give_consent'    => 'community_memberships#give_consent', as: :give_consent
    get  '/community_memberships/access_denied'   => 'community_memberships#access_denied', as: :access_denied

    get  '/community_memberships/check_email_availability_and_validity' => 'community_memberships#check_email_availability_and_validity'
    get  '/community_memberships/check_invitation_code'                 => 'community_memberships#check_invitation_code'

    namespace :paypal_service do
      resources :checkout_orders do
        collection do
          get :success
          get :cancel
          get :success_processed
        end
      end
    end

    namespace :admin do
      get '' => "getting_started_guide#index"
      
      resources :payment_preferences, only: [:index], param: :payment_gateway do
        collection do
          put :common_update
          put :update_stripe_keys
        end
        member do
          get :disable
          get :enable
        end
      end
      get  "/paypal_preferences" => redirect("/%{locale}/admin/payment_preferences")
      get  "/paypal_preferences/account_create"       => "paypal_preferences#account_create"
      get  "/paypal_preferences/permissions_verified" => "paypal_preferences#permissions_verified"
      
      get   "/settings" => "communities#settings",        as: :settings
      patch "/settings" => "communities#update_settings", as: :update_settings

      get "getting_started_guide"                        => "getting_started_guide#index",                  as: :getting_started_guide
      get "getting_started_guide/slogan_and_description" => "getting_started_guide#slogan_and_description", as: :getting_started_guide_slogan_and_description
      get "getting_started_guide/cover_photo"            => "getting_started_guide#cover_photo",            as: :getting_started_guide_cover_photo
      get "getting_started_guide/filter"                 => "getting_started_guide#filter",                 as: :getting_started_guide_filter
      get "getting_started_guide/payment"                => "getting_started_guide#payment",                as: :getting_started_guide_payment
      get "getting_started_guide/listing"                => "getting_started_guide#listing",                as: :getting_started_guide_listing
      get "getting_started_guide/invitation"             => "getting_started_guide#invitation",             as: :getting_started_guide_invitation

      get   "/look_and_feel/edit" => "communities#edit_look_and_feel",          as: :look_and_feel_edit
      patch "/look_and_feel"      => "communities#update_look_and_feel",        as: :look_and_feel
      get   "/details/edit"       => "community_customizations#edit_details",   as: :details_edit
      patch "/details"            => "community_customizations#update_details", as: :details
      get   "/new_layout"         => "communities#new_layout",                  as: :new_layout
      patch "/new_layout"         => "communities#update_new_layout",           as: :update_new_layout

      get   "/topbar/edit"        => "communities#topbar",                      as: :topbar_edit
      patch "/topbar"             => "communities#update_topbar",               as: :topbar

      get   "/landing_page"         => "communities#landing_page",                  as: :landing_page

      resources :communities do
        member do
          get :edit_welcome_email
          post :create_sender_address
          get :check_email_status
          post :resend_verification_email
          get :edit_text_instructions
          get :test_welcome_email
          get :social_media
          get :analytics
          put :social_media, to: 'communities#update_social_media'
          put :analytics, to: 'communities#update_analytics'
          delete :delete_marketplace

          get :topbar, to: redirect("/admin/topbar/edit")
          put :topbar, to: "communities#update_topbar" # PUT request, no redirect
          get :menu_links, to: redirect("/admin/topbar/edit")
          put :menu_links, to: "communities#update_topbar" # PUT request, no redirect

          get :getting_started, to: redirect('/admin/getting_started_guide')

sharetribe/app/models/community_customization.rb
# == Schema Information
#
# Table name: community_customizations
#
#  id                                         :integer          not null, primary key
#  community_id                               :integer
#  locale                                     :string(255)
#  name                                       :string(255)
#  slogan                                     :string(255)
#  description                                :text(65535)
#  created_at                                 :datetime         not null
#  updated_at                                 :datetime         not null
#  blank_slate                                :text(65535)
#  welcome_email_content                      :text(65535)
#  how_to_use_page_content                    :text(16777215)
#  about_page_content                         :text(16777215)
#  terms_page_content                         :text(16777215)
#  privacy_page_content                       :text(16777215)
#  signup_info_content                        :text(65535)
#  private_community_homepage_content         :text(16777215)
#  verification_to_post_listings_info_content :text(16777215)
#  search_placeholder                         :string(255)
#  transaction_agreement_label                :string(255)
#  transaction_agreement_content              :text(16777215)
#
# Indexes
#
#  index_community_customizations_on_community_id  (community_id)
#

class CommunityCustomization < ApplicationRecord

  # Set sane limits for content length. These are either driven by
  # column length in MySQL or, in case of :mediumtext type, set low
  # enough to prevent excess storage usage.
  validates_length_of :blank_slate, maximum: 65535
  validates_length_of :welcome_email_content, maximum: 65535
  validates_length_of :how_to_use_page_content, maximum: 262140
  validates_length_of :about_page_content, maximum: 262140
  validates_length_of :terms_page_content, maximum: 393210
  validates_length_of :privacy_page_content, maximum: 262140
  validates_length_of :signup_info_content, maximum: 65535
  validates_length_of :private_community_homepage_content, maximum: 262140
  validates_length_of :verification_to_post_listings_info_content, maximum: 262140
  validates_length_of :transaction_agreement_label, maximum: 255
  validates_length_of :transaction_agreement_content, maximum: 262140

  belongs_to :community

  CONTENT_FIELDS = %i(
    blank_slate
    welcome_email_content
    how_to_use_page_content
    about_page_content
    terms_page_content
    privacy_page_content
    signup_info_content
    private_community_homepage_content
    verification_to_post_listings_info_content
    search_placeholder
    transaction_agreement_label
    transaction_agreement_content
  )

end

sharetribe/app/controllers/admin/community_customizations_controller.rb
class Admin::CommunityCustomizationsController < Admin::AdminBaseController

  def edit_details
    @selected_left_navi_link = "tribe_details"
    # @community_customization is fetched in application_controller
    @community_customizations ||= find_or_initialize_customizations(@current_community.locales)
    all_locales = MarketplaceService::API::Marketplaces.all_locales.map { |l|
      {locale_key: l[:locale_key], translated_name: t("admin.communities.available_languages.#{l[:locale_key]}")}
    }.sort_by { |l| l[:translated_name] }
    enabled_locale_keys = available_locales.map(&:second)

    @show_transaction_agreement = TransactionService::API::Api.processes.get(community_id: @current_community.id)
      .maybe
      .map { |data| has_preauthorize_process?(data) }
      .or_else(nil).tap { |p| raise ArgumentError.new("Cannot find transaction process: #{opts}") if p.nil? }

    make_onboarding_popup
    render locals: {locale_selection_locals: { all_locales: all_locales, enabled_locale_keys: enabled_locale_keys, unofficial_locales: unofficial_locales }}
  end

  def update_details
    update_results = []
    analytic = AnalyticService::CommunityCustomizations.new(user: @current_user, community: @current_community)

    customizations = @current_community.locales.map do |locale|
      permitted_params = [
        :name,
        :slogan,
        :description,
        :search_placeholder,
        :transaction_agreement_label,
        :transaction_agreement_content
      ]
      locale_params = params.require(:community_customizations).require(locale).permit(*permitted_params)
      customizations = find_or_initialize_customizations_for_locale(locale)
      customizations.assign_attributes(locale_params)
      analytic.process(customizations)
      update_results.push(customizations.update_attributes({}))
      customizations
    end

    process_locales = unofficial_locales.blank?

    if process_locales
      enabled_locales = params[:enabled_locales]
      all_locales = MarketplaceService::API::Marketplaces.all_locales.map{|l| l[:locale_key]}.to_set
      enabled_locales_valid = enabled_locales.present? && enabled_locales.map{ |locale| all_locales.include? locale }.all?
      if enabled_locales_valid
        MarketplaceService::API::Marketplaces.set_locales(@current_community, enabled_locales)
      end
    end

    transaction_agreement_checked = Maybe(params)[:community][:transaction_agreement_checkbox].is_some?
    update_results.push(@current_community.update_attributes(transaction_agreement_in_use: transaction_agreement_checked))

    analytic.send_properties
    if update_results.all? && (!process_locales || enabled_locales_valid)

      # Onboarding wizard step recording
      state_changed = Admin::OnboardingWizard.new(@current_community.id)
        .update_from_event(:community_customizations_updated, customizations)
      if state_changed
        record_event(flash, "km_record", {km_event: "Onboarding slogan/description created"})

        flash[:show_onboarding_popup] = true
      end

      flash[:notice] = t("layouts.notifications.community_updated")
    else
      flash[:error] = t("layouts.notifications.community_update_failed")
    end

    redirect_to admin_details_edit_path
  end

  private

  def find_or_initialize_customizations(locales)
    locales.inject({}) do |customizations, locale|
      customizations[locale] = find_or_initialize_customizations_for_locale(locale)
      customizations
    end
  end

  def find_or_initialize_customizations_for_locale(locale)
    @current_community.community_customizations.find_by_locale(locale) || build_customization_with_defaults(locale)
  end

  def build_customization_with_defaults(locale)
    @current_community.community_customizations.build(
      slogan: @current_community.slogan,
      description: @current_community.description,
      search_placeholder: t("homepage.index.what_do_you_need", locale: locale),
      locale: locale
    )
  end

  def unofficial_locales
    all_locales = MarketplaceService::API::Marketplaces.all_locales.map{|l| l[:locale_key]}
    @current_community.locales.select { |locale| !all_locales.include?(locale) }
      .map { |unsupported_locale_key|
        unsupported_locale_name = Sharetribe::AVAILABLE_LOCALES.select { |l| l[:ident] == unsupported_locale_key }.map { |l| l[:name] }.first
        {key: unsupported_locale_key, name: unsupported_locale_name}
      }
  end

  def has_preauthorize_process?(processes)
    processes.any? { |p| p[:process] == :preauthorize }
  end
end

sharetribe/app/views/admin/community_customizations/_locale_input_fields.haml
- # locals:  header, available_locales, input_name, translations, info_text
- # optional locals: maxlength
.translation-wrapper
  - if header.present?
    .input-header
      = header
  = render :partial => "layouts/info_text", :locals => { :text => info_text.html_safe }
  - translations.each do |language_key, value|
    .row
      - if translations.size > 1
        .name-locale-label.col-2
          = label_tag "community_customizations[#{language_key}][#{input_name}]", value[:language], class: input_classes + ' label'
      .name-locale-text_field.col-10
        = text_field_tag "community_customizations[#{language_key}][#{input_name}]",
          value[:translation], class: input_classes, maxlength: defined?(maxlength) ? maxlength : nil

sharetribe/app/views/admin/community_customizations/_locale_input_textarea.haml
- # locals:  translations, input_name, info_text, input_classes
.translation-wrapper
  .input-header
    = header
  = render :partial => "layouts/info_text", :locals => { :text => info_text.html_safe }
  - translations.each do |language_key, value|
    .row
      - if translations.size > 1
        .name-locale-label.col-2
          = label_tag "community_customizations[#{language_key}][#{input_name}]", value[:language], class: input_classes + ' label'
      .name-locale-textarea.col-10
        = text_area_tag "community_customizations[#{language_key}][#{input_name}]", value[:translation], class: input_classes

sharetribe/app/views/admin/community_customizations/_locale_selection.haml
%div.locale-selection
  .input-header
    = t("admin.communities.edit_details.enabled_languages")

  - if unofficial_locales.blank?
    - content_for :extra_javascript do
      :javascript
        ST.updateLocales(#{enabled_locale_keys.to_json.html_safe});
        var selectize = $('#locale-selection').selectize({plugins: ['remove_button'], items: #{enabled_locale_keys.to_json.html_safe}})[0].selectize;
        selectize.on("change", function(value) {
          defaultLanguage = value ? selectize.options[value[0]].text.trim() : "-";
          $(".selected-default-language-name").text(defaultLanguage);
          ST.updateLocales(value);
          $('#edit_community').valid();
        });
    = render :partial => "layouts/info_text", :locals => { :text => t("admin.communities.edit_details.enabled_languages_description") }
    .row
      .col-10
        %select.locale-selection__input-widget.required{ multiple: true, name: "enabled_locales[]", id: "locale-selection" }
          - all_locales.each do |locale|
            %option{ value: locale[:locale_key] }
              = locale[:translated_name]
        %p#selected-default-language{ style: "clear: both;" }
          = t("admin.communities.edit_details.default_language") + ": "
          %span.selected-default-language-name
            = t("admin.communities.available_languages.#{enabled_locale_keys.first}")
  - else
    .row
      .col-10
        = render :partial => "layouts/info_text", :locals => { :text => t('admin.communities.edit_details.language_selection_disabled', languages: unofficial_locales.map{|locale| locale[:name]}.join(', ') ) }

sharetribe/app/views/admin/community_customizations/edit_details.haml
- content_for :javascript do
  ST.initializeCommunityCustomizations();

- content_for :title_header do
  %h1
    = t("layouts.admin.admin")
    = "-"
    = t("admin.communities.edit_details.community_details")

= render partial: 'layouts/onboarding_popup_wrapper'
= render :partial => "admin/left_hand_navigation", :locals => { :links => admin_links_for(@current_community) }

.left-navi-section
  %h2= t("admin.communities.edit_details.edit_community", :community_name => @current_community.name(I18n.locale))
  = form_tag admin_details_path, method: :patch, id: "edit_community" do |form|

    = render partial: "locale_selection",    locals: locale_selection_locals
    = render partial: "locale_input_fields", locals: community_name_locals
    = render partial: "locale_input_fields", locals: community_slogan_locals
    = render partial: "locale_input_fields", locals: community_description_locals
    = render partial: "locale_input_fields", locals: community_search_placeholder_locals

    - if @show_transaction_agreement
      .row
        .col-12
          = label_tag "transaction_label", t("admin.communities.edit_details.transaction_agreement"), class: "input"
          = check_box_tag "community[transaction_agreement_checkbox]", @current_community.transaction_agreement_in_use?, @current_community.transaction_agreement_in_use?, class: "checkbox-row-checkbox"
          = label_tag "community[transaction_agreement_checkbox]", t("admin.communities.edit_details.transaction_agreement_checkbox"), class:"checkbox-row-label"

      = render partial: "locale_input_fields", locals: transaction_agreement_label_locals
      = render partial: "locale_input_textarea", locals: transaction_agreement_text_locals

    .row
      .col-12
        = button_tag t("admin.communities.edit_details.save")


= render :partial => "people/help_texts", :collection => ["invite_only_help_text"], :as => :field